let proverbs = [
	'Fogatlan ló nem tud fűbe harapni.',
	'Magas lóról, a törpe is lefelé néz.',
	'Nagyot mondani a kicsi is tud.',
	'Ha egyedül vagy, akkor ne próbáld bekeríteni az ellenséget!',
	'Vesszőparipától ne várjunk lódobogást.',
	'Skalpot szerezni, a másik dakota övéről a legkönnyebb.',
	'A lóvá tett ellenségen még nem lehet bölényt üldözni.',
	'Szembeszélben ne köpködj.',
	'A békepipának nem a füstje számít.',
	'Mielőtt vágtába csapsz, nézd meg, hogy a lovon ülsz-e.',
	'Mielőtt hadi ösvényre lépsz, jól nézd meg, ki kövezte ki.',
	'Ha ellenségeid lőtávolságon belül vannak, akkor te is.',
	'Ha leölted az utolsó bölényt, utoljára laksz jól.',
	'Nem elég az ígéret! A bölényvadászathoz bölény is kell!',
	'A porrá zúzott medvehere akkor tesz igazán gyorssá, ha a medve még él.',
	'Vak lóval ne vágtass a fák közé!',
	'A döglött ló is lehet engedelmes, csak azt kell mondanod neki: Fekszik!',
	'A szélsőség még mindig gusztusosabb, mint a belsőség.',
	'Mi ismerjük a jó utat! Csak előbb meg kell építenünk.',
	'Vágtató lovon, jobban kell kapaszkodni.',
	'A döglött dakota ló sohasem botlik.',
	'Jobb ma egy holnap, mint holnap egy tegnap.',
	'Ha már kiástad a csatabárdot, temesd be a gödröt!',
	'A múltat nem lehet megmásítani, de másképpen magyarázni mindig sikerül.',
	'Nem erőszak a disznótor, legfeljebb a disznónak!',
	'Könnyebb versenyt futni a bölénnyel, mint a széllel.'
];